project:
  type: website
  output-dir: docs

website:
  title: "Links"
  sidebar:
    style: "docked"
    search: false
    background: "#9A9AEB"
    contents:
      - text: Memorial Page <i class="bi bi-box-arrow-up-right"></i>
        href: "https://www.dignitymemorial.com/obituaries/kansas-city-mo/ruth-mitchell-12935221"
      - text: Photo slideshow
        href: slide-show.qmd


format:
  html:
    grid:
      sidebar-width: 400px
    theme:
      - cosmo
      - assets/custom.scss
    fig-align: center
